# Generated by Django 4.1.13 on 2023-11-22 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateField(default=django.utils.timezone.now)),
                ('date', models.PositiveIntegerField(default=0, null=True)),
                ('hour', models.PositiveIntegerField(default=0, null=True)),
                ('text', models.CharField(choices=[('休暇', '休暇'), ('遅刻', '遅刻'), ('早退', '早退')], default='休暇', max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paidholidays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarryOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carry_over', models.PositiveIntegerField(default=0, null=True)),
                ('author', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carryover', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
