# Generated by Django 3.0.5 on 2023-09-30 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarryOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carry_over', models.PositiveIntegerField(default=0, null=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaidHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateField(default=django.utils.timezone.now)),
                ('date', models.PositiveIntegerField(default=0, null=True)),
                ('hour', models.PositiveIntegerField(default=0, null=True)),
                ('text', models.CharField(choices=[('休暇', '休暇'), ('遅刻', '遅刻'), ('早退', '早退')], default='休暇', max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
