# Generated by Django 4.1.13 on 2023-11-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paidholidays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carryover',
            name='author',
        ),
        migrations.RemoveField(
            model_name='paidholidays',
            name='author',
        ),
    ]
