# Generated by Django 4.2.13 on 2025-07-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paidholidays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidholidays',
            old_name='update',
            new_name='update_start',
        ),
    ]
