# Generated by Django 4.2.13 on 2025-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidholidays', '0002_rename_update_paidholidays_update_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidholidays',
            name='update_end',
            field=models.DateField(null=True),
        ),
    ]
