# Generated by Django 4.1.13 on 2024-04-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidholidays', '0002_remove_carryover_author_remove_paidholidays_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carryover',
            old_name='carry_over',
            new_name='date',
        ),
        migrations.AddField(
            model_name='carryover',
            name='hour',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='carryover',
            name='min',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
