# Generated by Django 4.2.13 on 2025-07-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paidholidays', '0003_paidholidays_update_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidholidays',
            old_name='update_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='paidholidays',
            old_name='update_start',
            new_name='start_date',
        ),
    ]
