on:
  push:
    branches: 'main'
    paths: 'backend/**'

env:
  image-name-nginx: nginx
  image-name-web-back: web-back

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      nginx: ${{ steps.filter.outputs.nginx }}
      web-back: ${{ steps.filter.outputs.web-back }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            nginx:
              - 'backend/nginx/**'
            web-back:
              - 'backend/web-back/**'

  image-push-nginx:
    if: ${{ needs.changes.outputs.nginx == 'true' }}
    needs: changes
    defaults:
      run:
        working-directory: backend/nginx
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'

      - name: setup google cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: configure docker for artifact registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: docker build
        run: docker build -f Dockerfile -t asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITRY_ID }}/${{ env.image-name-nginx }}:v1 .

      - name: push
        run: docker push asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITRY_ID }}/${{ env.image-name-nginx }}:v1

  image-push-web-back:
    if: ${{ needs.changes.outputs.web-back == 'true' }}
    needs: changes
    defaults:
      run:
        working-directory: backend/web-back
    env:
      image-name: web-back
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'

      - name: setup google cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: configure docker for artifact registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: docker build
        run: docker build -f Dockerfile -t asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITRY_ID }}/${{ env.image-name-web-back }}:v1 .

      - name: push
        run: docker push asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITRY_ID }}/${{ env.image-name-web-back }}:v1

  deploy:
    if: ${{ always() }}
    needs: [image-push-nginx, image-push-web-back]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: deploy as sidecar
        run: |
          gcloud beta run deploy nenq-project \
            --project ${{ secrets.PROJECT_ID }} \
            --region asia-northeast1 \
            --service-account ${{ secrets.SERVICE_ACCOUNT }} \
            --container nginx \
            --image='${{ env.image-name-nginx }}' \
            --port='8080' \
            --container web-back \
            --image='${{ env.image-name-web-back }}'
